apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echoserver
  namespace: argocd
spec:
  project: default
  source:
    path: example/kpt-app/
    repoURL: https://github.com/bluebrown/argocd-cmp-kpt
    targetRevision: main
    plugin: {}
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
