apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# deploy the resources to the argocd namespace
namespace: argocd
# use the stable base installation
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# use the component which contains the patch
# to configure the CMP on the ArgoCD repo server
components:
  - component/
